=== stefandmn/AREasy/src/doc/help/action.dtd
<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<!DOCTYPE help [
		<!ELEMENT help (name|description|syntax|options|options1|options2|samples)*>
		<!ATTLIST help
				inherits CDATA #IMPLIED>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT syntax (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT options (option)*>
		<!ELEMENT options1 (option)*>
		<!ELEMENT options2 (option)*>
		<!ELEMENT samples (sample)*>
		<!ELEMENT option (#PCDATA)>
		<!ELEMENT sample (#PCDATA)>
		<!ATTLIST option
				key CDATA #REQUIRED
				type (string|number|date|bool|list) #REQUIRED
				defvalue CDATA #IMPLIED
				selvalues CDATA #IMPLIED
				description CDATA #IMPLIED>
		<!ATTLIST sample
				code CDATA #REQUIRED
				description CDATA #REQUIRED>
]>

=== stefandmn/AREasy/src/doc/help/system/start.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help>
	<name>Start</name>
	<description>Start action is used to start the local AREasy server instance.</description>
	<syntax>areasy -action start [-javaxms Value1] [-javaxmx Value2] [-javad param1=Value2 param2=Value2]</syntax>
	<options>
		<option key="javaxms" type="string" description="initial java heap size for the server instance"/>
		<option key="javaxms" type="string" description="maximum java heap size for the server instance"/>
		<option key="javad" type="string" description="additional runtime options for java virtual machine (could be a list of '-D' java runtime parameters)"/>
	</options>
	<options1>
		<option key="host" type="string" description='Overwrites the value of "app.server.host" parameter'/>
		<option key="port" type="string" description='Overwrites the value of "app.server.port" parameter'/>
		<option key="arserver" type="string" description='Replaces the value of "app.server.default.arsystem.server.name" parameter'/>
		<option key="aruser" type="string" description='Replaces the value of "app.server.default.arsystem.user.name" parameter'/>
		<option key="arpassword" type="string" description='Replaces the value of "app.server.default.arsystem.user.name" parameter'/>
		<option key="arport" type="string" description='Replaces the value of "app.server.default.arsystem.port.number" parameter'/>
		<option key="loglevel" type="string" description='Overwrites the value of "app.runtime.logger.level" parameter'/>
		<option key="logformatter" type="string" description='Overwrites the value of "app.runtime.logger.formatter" parameter'/>
	</options1>
	<samples>
		<sample code='areasy -action start'
				description="Starts local runtime server instance"/>
		<sample code='areasy -action start -javaxms 128M -javaxmx 1024M -javad "areasy.home=/opt/areasy" "data.home=/opt/arasy/work/data"'
				description='Starts runtime server with xms and xmx java runtime values, plus additional java runtime "-D" values'/>
	</samples>
</help>

=== stefandmn/AREasy/src/doc/help/itsm/admin/supportgroupadmin.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help inherits="itsm/admin/baseenrollment.xml">
	<name>Support Group Administration</name>
	<description>
		This action is an ITSM utility, designed to create or update support groups and to manage their members and related details.
	</description>
	<syntax>
		areasy -action supportgroupadmin
	</syntax>
	<options>
		<option key="runcondition" type="string" description="Describes the Velocity condition to allow the execution of action's operation. The evaluation is performed before action operation and contains a context with all input parameters and read attributes  for the particular CoreItem instance processed by the requested operation"/>
		<option key="operation" type="string" selvalues="setentity,setmembers,delmembers,setfrole,delfrole" defvalue="setentity" description="Execution mode or this action"/>
		<option key="sgroupcompany" type="string" description="Current support group company. In addition the action supports another alias for this option: supportgroupcompany"/>
		<option key="sgrouporganisation" type="string" description="Current support group organisation. In addition the action supports another alias for this option: supportgrouporganisation"/>
		<option key="sgroupname" type="string" description="Current support group name. In addition the action supports some aliases for this option: sgroup, supportgroup, supportgroupname"/>
		<option key="sgroupid" type="string" description="Current support group id. In addition the action supports some aliases for this options: supportgroupid"/>
		<option key="role" type="string" description=""/>
		<option key="apcode" type="string" description="applicationcode"/>
		<option key="status" type="string" description=""/>
		<option key="alias" type="list" description=""/>
		<option key="default" type="bool" description=""/>
		<option key="supportstaff" type="bool" description=""/>
		<option key="findusers" type="bool" description=""/>
	</options>
</help>

=== stefandmn/AREasy/src/doc/help/system/install.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help>
	<name>Install</name>
	<description>
Install action has the main scope to install AREasy packages on the local instance (using RUNTIME mode) or a remote AREasy server instance. An installation procedure with this action brings additional resources in configuration area and additional libraries.
An AREasy package is a ARJ file (a Jar archive) that contains resources in maximum four areas:
 - /bin = new or updated binary files
 - /cfg = configuration resources that could be configuration sectors and other files and folders.
 - /doc = documentation and sample files
 - /libs = java libraries (Jar files)that will be appended to the application classpath

During installation process the action will append new configuration sectors in the default.properties and will reload/refresh the entire configuration structure. Also, Java libraries that will be deployed on libraries container will be automatically  loaded without server restart.
After installation the package will be fully functional without server restart. The installation procedure works also for remote server instances.

Note: Environment option should be used only if you know that your package has been built with specific configuration parameters for your environment (that means if package includes "install[-environment].properties" configuration file(s))
	</description>
	<syntax>areasy -action install -file ARJFile [-environment EnvironmentName]</syntax>
	<options>
		<option key="file" type="string" description="ARJ file located on the file system"/>
		<option key="environment" type="string" description="It is the name (string code) of the environment that it's used to apply custom configurations. Each environment (production, test, etc.) could have separate and specific configuration and in order to distinguish between them you have to specify a value for this option. By default is considered 'production' environment."/>
	</options>
	<samples>
		<sample code="areasy -action install -file c:\\areasy-com.arj"
				description="Installs 'areasy-com' package on the local server instance or using Runtime execution mode"/>
		<sample code='areasy -action install -file c:\\areasy-com.arj -host VM001 -aruser Demo -arpassword "1234"'
				description="Installs 'areasy-com' package on a remote server (host is VM001)"/>
		<sample code='areasy -action install -file c:\\areasy-com.arj -environment test -host VM001 -aruser Demo -arpassword "1234"'
				description="Installs 'areasy-com' package on a remote server (host is VM001) but for testing environment (configuration - will apply all configuration options from 'install-test.properties' file, included in the ARJ file)"/>
	</samples>
</help>
