=== stefandmn/AREasy/src/doc/help/action.dtd
<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<!DOCTYPE help [
		<!ELEMENT help (name|description|syntax|options|options1|options2|samples)*>
		<!ATTLIST help
				inherits CDATA #IMPLIED>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT syntax (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT options (option)*>
		<!ELEMENT options1 (option)*>
		<!ELEMENT options2 (option)*>
		<!ELEMENT samples (sample)*>
		<!ELEMENT option (#PCDATA)>
		<!ELEMENT sample (#PCDATA)>
		<!ATTLIST option
				key CDATA #REQUIRED
				type (string|number|date|bool|list) #REQUIRED
				defvalue CDATA #IMPLIED
				selvalues CDATA #IMPLIED
				description CDATA #IMPLIED>
		<!ATTLIST sample
				code CDATA #REQUIRED
				description CDATA #REQUIRED>
]>

=== stefandmn/AREasy/src/doc/help/ars/admin/syscaller.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help inherits="action.xml">
	<name>AR System Caller</name>
	<description>
		This action is an ARS utility, designed to execute different system internal objects (escalations, filter processes, etc.).
	</description>
	<syntax>
		areasy -action syscaller [-process ProcessName [-wait] -expression ExpressionCommandLine] [-escalation EscalationObjectName]
	</syntax>
	<options>
		<option key="process" type="string" description="Filter process name (as it is described in the documentation) to be executed"/>
		<option key="wait" type="bool" description="Waits until the process execution is finished or returns the control to the caller"/>
		<option key="params" type="string" description="Specifies additional parameters needed by the process to be executed"/>
		<option key="escalation" type="string" description="Escalation object name to be triggered adhoc against of designed time or calendar trigger"/>
	</options>
	<samples>
		<sample code="areasy -action syscaller -process 'Application-Generate-GUID'" description="Generates application GUID"/>
	</samples>
</help>

=== stefandmn/AREasy/src/doc/help/system/process.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help>
	<name>Process</name>
	<description>
Process action has been designed to execute external (operating system) processes.
The process action could be called if the runtime server runs locally or if you'll provide admin credentials (user credentials used to connect to the AR System instance).

Attention: if the external command waits an user input the action will remain stacked. For instance, if you'll call a GUI application the action return the control to the runtime manager only when the main process thread is die (when the GUI will be closed).
	</description>
	<syntax>areasy -action process -cmd CommandLine</syntax>
	<options>
		<option key="cmd" type="string" description="It is the parameter that fully describes the external command line."/>
	</options>
	<samples>
		<sample code='areasy -action process -cmd "sc start AREasy"' description="Starts AREasy windows service"/>
		<sample code='areasy -action process -cmd "sc stop AREasy"' description="Stops AREasy windows service"/>
		<sample code="areasy -action process -cmd 'help'" description="Executes and display the output of 'help' Windows command"/>
		<sample code="areasy -action process -cmd 'calc.exe'" description="Runs Windows Calculator application, waits until it will be close and then will return the control"/>
	</samples>
</help>

=== stefandmn/AREasy/src/doc/help/ars/data/filewrapper.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help inherits="ars/data/basedata.xml">
	<name>File Wrapper</name>
	<description>File wrapper to read file content and to pass it to other action to execute transactions</description>
	<syntax>
		areasy -action filewrapper
		[-file FilePath -startindex StartIndex [-endindex EndIndex] [-pageindex FileWorksheet -force]]
		-call sub.action ...sub action parametrization.. [sleep SleepInMilliseconds]
	</syntax>
	<options>
		<option key="inputfile" type="string" description="Aliases for this option are: parserfile, file. Indicates the path of the data file"/>
		<option key="parsertype" type="string" description="Identifies a particular files, if this option is not specified the file type and the corresponding parser will be detected based on file extension. SUpported data files are: comma separated, Excel (2003 format) and tab or delimiter separated"/>
		<option key="when" type="string" description="Null value of conditional expression that allows to call wrapped action"/>
		<option key="call" type="string" description="Alias for this option is: subaction. It specify the action that will be called by this wrapper thta can use the data records extracted by file parser and reader"/>
		<option key="limit" type="number" description="Indicates the numer of records that will be read from the specified file"/>
		<option key="sleep" type="number" description="Describes a sleep time (in seconds) between two consecutive reads from the file"/>
	</options>
	<samples>
		<sample code="areasy -action filewrapper -file /tmp/data.csv -call formdata -operation create -D1001 ${A} -D1002 ${B} -D1003 ${C} -D1004 ${D}" description="Reads content of data.csv file (line by line) and pass the data to 'formadata' action in order to execute Create operation. The data is used like a spreadsheet with columns A, B, C, etc. within variables: first column = ${A}, second column = ${B}, etc."/>
	</samples>
</help>

=== stefandmn/AREasy/src/doc/help/system/config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help>
	<name>Config</name>
	<description>
Config action is used to set the configuration properties from configuration files and to reload server or runtime configuration entries. Config action runs in security mode that means could be called locally as it is or remotely, if you'll provide admin credentials (user credentials used to connect to the AR System instance).
Instead of clear text password could be also provided the obfuscated version. As is described in the second example, _Demo_ user and _1234_ password must be the values of `app.server.default.arsystem.user.name` and `app.server.default.arsystem.user.password` from `default.properties` configuration sector.
	</description>
	<syntax>areasy -action config [-reload] [-property ConfigurationProperty] [-sector ConfigurationSector] [-value ConfigurationValue] [-values Value1 Value2 .. ValueN>]</syntax>
	<options>
		<option key="reload" type="bool" defvalue="off" description="Reloads configuration entries after they are changed and saved in th configuration sector(s)"/>
		<option key="sector" type="string" description="Specifies the configuration sector that have to be changed"/>
		<option key="property" type="string" description="This is the option that indicates the property key that will be modified"/>
		<option key="values" type="string" description="The list of values that have to be associated to the specified property key"/>
		<option key="value" type="string" description="The new value of the specified property key. If are specified both options (-value and -values) the list of values will be consolidated"/>
	</options>
	<samples>
		<sample code="areasy -action config -reload"
				description="Reloads server configuration for a local AREasy server"/>
		<sample code="areasy -action config -reload -aruser Demo -arpassword 1234"
				description="Reloads server configuration for a remote AREasy server instance"/>
		<sample code='areasy -action config -property "app.server.default.arsystem.server.name" -value "localhost" -reload'
				description="Sets the property key that specify what AR Server server is connected to the AREasy instance and than reloads/refreshes configuration properties from AREasy server instance"/>
	</samples>
</help>

=== stefandmn/AREasy/src/doc/help/system/help.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help>
	<name>Help</name>
	<description>
Help action shows and describes standard command line and related parameters. Also, using [-inventory] you can get the list of all registered actions.
If in the command line will be included [-call ActionName] will be displayed the help text of returned by that specified action name.
In case of [-call ...] parameter is not specified, Help action displays this text.
	</description>
	<syntax>
		areasy [-runtime] -action help
		[-call [WrappedAction] [-export [-outputfile FileName] | [-exportformat txt|html|md|pdf]]
	</syntax>
	<options>
		<option key="inventory" type="bool" defvalue="off" description="Returns a list of all registered actions"/>
		<option key="call" type="string" description="Specifies a registered action that is called to retrieve its help document. 'subaction' parameter alias could be used in order to obtain the same thing"/>
		<option key="export" type="bool" defvalue="off" description="Export help content into a supported document format (see 'exportformat' options)"/>
		<option key="outputfile" type="string" description="Exports help document related to the action specified by 'call' parameter into the specified file path and name"/>
		<option key="exportformat" type="string" description="In case the 'outputfile' is null (not specified) this parameter could mention the file format for the help document requested for export (through file extension)"/>
	</options>
	<samples>
		<sample code='areasy -action help'
				description="Displays the whole help text of Help action called from AREasy server. This is a client call to the server that is described in the configuration file"/>
		<sample code='areasy -action help -inventory'
				description="Displays the list of registered action on the AREasy server. This is a client call to the server that is described in the configuration file"/>
		<sample code='areasy -action help -call file.wrapper'
				description="Displays the help text delivered by the data.wrapper.file action, from the server instance described in the configuration file"/>
		<sample code='areasy -runtime -action help -inventory'
				description="Display the list of registered action on the local AREasy distribution, called as a Runtime instance"/>
		<sample code='areasy -host localhost -action help'
				description="Displays the complete help text of Help action called from 'localhost' AREasy server instance. The action is execute on that server and the answer (this help text) is returned in the client console (where this command has been executed)"/>
	</samples>
</help>

=== stefandmn/AREasy/src/doc/help/ars/data/basedata.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help inherits="action.xml">
	<options1>
		<option key="Q" type="string" description="Query prefix identifier to query after a field id"/>
		<option key="D" type="string" description="Data prefix identified to push value of specific field id"/>
		<option key="F" type="string" description="Data prefix identified to push file object to a specific field id"/>
		<option key="DC" type="string" description="Data prefix identified to push value of specific field id but only for Create events"/>
		<option key="DU" type="string" description="Data prefix identified to push value of specific field id but only for Update events"/>
		<option key="partforms" type="list"  description="Define the list of multi-part forms. The syntax is the following: -partforms Par1@FormName1;Part2@FormName2;..;PartX@FormNameX"/>
		<option key="multipart" type="bool" description="Activate multi-part form extension"/>
		<option key="ignorenullvalues" type="bool" description="Ignore null values from input during transaction execution"/>
		<option key="ignoreunchangedvalues" type="bool" description="Ignore unchanges values in comparison with input values from instantiation or from read"/>
		<option key="simplified" type="bool" description="Specify if the transaction will use 'fast return' mechanism avoiding to re-read the submitted or updated record."/>
		<option key="firstmatchreading" type="bool" description="Activate first match operation and disable exact match opeartion"/>
		<option key="exactmatchreading" type="bool" description="Activate exact match operation and disable first match opeartion"/>
		<option key="entity" type="string" selvalues="company,region,site,organisation,sgroup,people,product,service,configurationitem,inventorylocation" description="Indicate what particular entity structure will process the data"/>
		<option key="classid" type="string" description="In case you'll process CMDB data this attribute can identify class id (or class keyword) in order to detect the other details (forms, fields, etc.)"/>
		<option key="formname" type="string" description="AR form name to process the transaction"/>
		<option key="ignorenulls" type="list" description="Specify to not fill in the entity structure with null data"/>
		<option key="force" type="bool" description="Force transactions in case of the main transaction contains a cycle that repeats sub-transactions"/>
		<option key="mergetype" type="string" selvalues="duperror,dupnewid,dupoverwrite,dupmerge" description="Specify type of merge transaction"/>
		<option key="mergeoptions" type="list" selvalues="norequired,nopattern,noworkflow" description="Specify additional merge options"/>
		<option key="datamaps" type="list" description="Load data maps from external files"/>
	</options1>
</help>

=== stefandmn/AREasy/src/doc/help/itsm/admin/abs.enrollment.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "C:\Users\S.Damian\Workspace\Development\AREasy3\AREasy\src\doc\help\action.dtd">

<!--
  ~ Copyright (c) 2007-2018 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help inherits="action.xml">
	<options>
		<option key="login" type="string" description="Specifies a login name registered in Remedy. This option has 'username' alias."/>
		<option key="logins" type="list" description="Specifies a list of login names registered in Remedy. This option has 'usernames' alias."/>
		<option key="userfieldid" type="string" description="Specifies a field id from a specified form that will be used to identify an user account"/>
		<option key="userfieldvalue" type="string" description="Specifies the field value that will be used to create the qualification string that will be used to idenfy the user account"/>
		<option key="userqualification" type="string" description="Defines a custom qualification criteria to identify the user account"/>
		<option key="userform" type="string" description="Specifies the formname that will be used in order to define the structured qualification using 'userfieldid' and 'userfieldvalue' options. This option has 'userformname' alias"/>
		<option key="excludeusers" type="list" description="Defines a list of user account that could be excluded in case of the user list is returned dynamically, based on custom qualifications"/>
	</options>
</help>

=== stefandmn/AREasy/src/doc/help/system/echo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help>
	<name>Echo</name>
	<description>
Echo action is usually used to check if an AREasy server instance is running or not. If is running the server will return a log message having the following pattern:
"Echo message from AREasyHostName:AREasyPort"
	</description>
	<syntax>areasy -action echo [-signal] [-inout]</syntax>
	<options>
		<option key="inout" type="bool" defvalue="off" description="It is parameter that will print out as a log message all input parameters (from command line) and their values"/>
		<option key="signal" type="bool" defvalue="off" description="It is provided to the action to return a data value that is '0'. This parameter is usually used to check in real time system interoperability for complex AREasy configuration. As an example this method could be used be AREasy FILTERAPI module in order to send a real message to the Remedy server that AREasy is online and could process external calls"/>
		<option key="arsystem" type="bool" defvalue="off" description="Checks the connectivity to an AR System server"/>
	</options>
	<samples>
		<sample code="areasy -action echo" description="Checks server status and returns a log message"/>
		<sample code="areasy -action echo -signal" description="Checks server status and returns bit 0 as a value if the server is up (otherwise nothing) and server answer into a log message"/>
		<sample code="areasy -action echo -inout" description="Checks server status and returns input parameters as output value and server status as a log message"/>
	</samples>
</help>
