=== stefandmn/AREasy/src/doc/help/action.dtd
<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<!DOCTYPE help [
		<!ELEMENT help (name|description|syntax|options|options1|options2|samples)*>
		<!ATTLIST help
				inherits CDATA #IMPLIED>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT syntax (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT options (option)*>
		<!ELEMENT options1 (option)*>
		<!ELEMENT options2 (option)*>
		<!ELEMENT samples (sample)*>
		<!ELEMENT option (#PCDATA)>
		<!ELEMENT sample (#PCDATA)>
		<!ATTLIST option
				key CDATA #REQUIRED
				type (string|number|date|bool|list) #REQUIRED
				defvalue CDATA #IMPLIED
				selvalues CDATA #IMPLIED
				description CDATA #IMPLIED>
		<!ATTLIST sample
				code CDATA #REQUIRED
				description CDATA #REQUIRED>
]>

=== stefandmn/AREasy/src/doc/help/ars/data/formdata.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help inherits="ars/data/basedata.xml">
	<name>Form Data Operation</name>
	<description>Execute data transactions through a dedicated AR form</description>
	<syntax>
		areasy -action formdata -operation insert|update|delete|merge
		-form FormName [-id EntryId] [-Q10001 Values1 .. -Q1000N ValuesN] [-qualification "'7'=1"]
		-D10001 Values1 .. -D1000N ValuesN
	</syntax>
	<options>
		<option key="operation" type="string" selvalues="insert,update,delete,merge" description="Indicates type of transactions: insert, update, delete or merge"/>
		<option key="id" type="string" description="Identify form record by Request ID/Entry ID (field with Id 1)"/>
		<option key="qualification" type="string" description="Identify form record based on a specific qualification"/>
		<option key="chunk" type="string" description="A set of records fetched through a search having less number of records than total search operation is considered a chunk. Chunk option is used only with qualification flag and will shift the search starting from specific what chunk number"/>
		<option key="nextchunkid" type="string" description="Works only in conjunction with qualification and chunk options and a Request Id to be considered in search condition for the next chunk"/>
		<option key="limit" type="string" description="Limits the search operation (and implicitly for data fetching) to to a number of records"/>
		<option key="mergematchingfieldids" type="string" description="Specify a list of fields that will be considered for data matching"/>
		<option key="mergevaliddata" type="bool" description="Run merge operation validating data before merge (e.g. to exist, etc.)"/>
		<option key="createifnotexist" type="bool" description="For update operation creates the record if doesn't exist"/>
		<option key="updateifexists" type="bool" description="For create operation updates the record if it is already registwered"/>
	</options>
	<samples>
		<sample code="areasy -action ars.formdata -form TestForm -Q1000 'Key' -D8 'Info' -D1001 'Blue Color' -D1002 123 -operation create -updateifexists" description="Creates a new entry in TestForm form but checking previously if it is already created checking in field '1000' the keyword 'Key'"/>
		<sample code="areasy -action ars.formdata -form TestForm -qualification ||'1000'='Key' AND '7' = 0|| -D8 'Info' -D1001 'Blue Color' -D1002 123 -operation update -createifnotexist" description="Updates an entry in TestForm form identifying it using a custom qualification search. In case the record(s) is/are not identified through the qualification it will be created"/>
		<sample code="areasy -action ars.formdata -form TestForm -id 10000038764 -D8 'Info' -D1001 'Blue Color' -D1002 123 -operation update -createifnotexist" description="Updates an entry in TestForm form identifying it using a specific entry id. In case the record is not identified (more exacly the entry id doesn't exist) it will be created"/>
	</samples>
</help>

=== stefandmn/AREasy/src/doc/help/ars/admin/password.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help inherits="action.xml">
	<name>AR Password Manager</name>
	<description>
		This action is an ARS utility, designed to encrypt or to decrypt AR configuration keys and passwords. Please notice that this action needs connection to the server that manages that key or password.
	</description>
	<syntax>
		areasy -action password -operation encrypt|decrypt -key [KeyOrPassword]
	</syntax>
	<options>
		<option key="operation" type="string" selvalues="encrypt,decrypt" defvalue="" description="Execution mode or this action (encrypt or decrypt keys and passwords)"/>
		<option key="type" type="list" selvalues="field,system" description="Describe type of key that is manipulated: key for password field (this is the default value) and key for system operations"/>
		<option key="key" type="string" description="Key or password that will be applied to encryption or decryption procedure"/>
	</options>
	<samples>
		<sample code="areasy -action password -operation encrypt -key test" description="Encrypt 'test' string in ARSystem format to become a classic AR password"/>
		<sample code="areasy -action password -operation encrypt -key test -arserver ars1 -aruser Demo" description="Encrypt 'test' string in ARSystem format to become a classic AR password but with explicit connection to a particular ARS server (and not relaying on the connection details defined in general runtime configuration)"/>
	</samples>
</help>

=== stefandmn/AREasy/src/doc/help/system/clean.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help>
	<name>Clean</name>
	<description>Clean action runs only in server mode and it executes garbage collector, removes temporary files, log files and also removes the cache objects.</description>
	<syntax>areasy -action clean [-olderthan 10|20|..(in days)] [-force]</syntax>
	<options>
		<option key="force" type="bool" defvalue="off" description="Force to remove all objects from the cache layer. Otherwise will remove only expired objects."/>
		<option key="olderthan" type="number" description="Specifies a period (in days) that will be considered to remove the log files and also the temporary files"/>
	</options>
	<samples>
		<sample code="areasy -action clean" description="Removes all expired objects from cache"/>
		<sample code="areasy -action clean -force" description="Removes all objects from cache"/>
	</samples>
</help>

=== stefandmn/AREasy/src/doc/help/system/status.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help>
	<name>Status</name>
	<description>Status action displays the environment details of the runtime instance or displays the current status of the AREasy server instance including details about runtime server execution channels</description>
	<syntax>areasy -action status [-environment] [-channels [true|channel id(s)]] [-channel ChannelNumber] [-call ActionName [-signal]] [-repeat Value [-sleep SleepTimeInMilliseconds]]</syntax>
	<options>
		<option key="signal" type="bool" defvalue="off" description="Returns bit 0 instead of read status message (that will become a log message). This option works together with -call or -channel(s)"/>
		<option key="sleep" type="number" description="After execution the action will wait the specified number of milliseconds till will return the control to the runtime management. This behaviour is applicable only if the action is running in client/server mode"/>
		<option key="call" type="string" description="Displays the status messages delivered by all channels that runs the specified action name"/>
		<option key="repeat" type="bool" defvalue="off" description="This option works only if -sleep has a value greater than 0 and when -call or -channel(s) options are included in the status interrogation. This option will repeat interrogation of channels list according to the specified repetition number and if this value is 0 the status message will loop continuously till no signal is found on all execution channels"/>
		<option key="channel" type="bool" defvalue="off" description="Displays the status message for the action that runs on the specified channel number"/>
		<option key="channels" type="string" description="If the option doesn't have value(s) it will display the list of execution channels, the actions that run on each channel and their status. In case of the option is asked with a value or a list of values it will return the real-time status message delivered by each action under execution"/>
		<option key="environment" type="bool" defvalue="off" description="Displays environment details about the runtime instance. If the action runs in client/server mode, the option will display also the figures about server execution channels. This option is default selected when the action is called without any switch. The option is skipped in case of is not specified explicitly and -channel(s) option is asked"/>
	</options>
	<samples>
		<sample code="areasy -action status"
				description="Displays environment details"/>
		<sample code="areasy -action status -channels"
				description="Displays channels execution list"/>
		<sample code="areasy -action status -environment -channels"
				description="Displays environment details and channels execution list"/>
		<sample code="areasy -action status -channels 3 5"
				description="Displays the status messages for channels 2 and 3"/>
		<sample code="areasy -action status -channel 2"
				description="Displays the status message for channel 2"/>
		<sample code='areasy -action status -call "data.wrapper.file"'
				description="Displays the status messages for all channels where 'data.wrapper.file' runs"/>
		<sample code="areasy -action status -channels 3 5 -sleep 3000 -repeat 5"
				description="Displays the status messages for channels 3 and 5 and repeat the interrogation 5 times, from 3 to 3 seconds"/>
		<sample code='areasy -action status -call "data.wrapper.file" -sleep 5000 -repeat 0'
				description="Displays the status messages for all channels where 'data.wrapper.file' runs and repeat the interrogation from 5 to 5 seconds will no one of these channels will have signal"/>
	</samples>
</help>

=== stefandmn/AREasy/src/doc/help/itsm/admin/delapppermission.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help inherits="itsm/admin/baseenrollment.xml">
	<name>Remove Application Permission</name>
	<description>The action is part of AR System management tools and it has the main goal to remove a specific application permission for one or many users. Application permission and also login Ids are validated before to be processed</description>
	<syntax>
		areasy -action delapppermission -permission ApplicationPermissionName -login val -logins val1 val2 ... valN
			-skipvalidation -findusers -excludeusers
	</syntax>
	<options>
		<option key="permission" type="string" description="Indicates the application permission name (e.g. 'Incident User') to be deleted from user permission list"/>
		<option key="findusers" type="bool" description="In case the login ids are not specified the system can detect the whole list of user that have the specified permission name"/>
		<option key="excludeusers" type="list" description="In case the user will be detected and you want to exclude a static list of user this option can be helpful"/>
		<option key="skipvalidation" type="bool" description="Skip the validation of specified permission"/>
	</options>
	<samples>
		<sample code="areasy -action delapppermission -permission 'Incident User'" description="Delete all incident User permissions from the system related to all found users"/>
		<sample code="areasy -action delapppermission -permission 'Incident User' -login appadmin" description="Delete incident User permission associated to appadmin user"/>
	</samples>
</help>

=== stefandmn/AREasy/src/doc/help/itsm/admin/supportgroup.administration.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "C:\Users\S.Damian\Workspace\Development\AREasy3\AREasy\src\doc\help\action.dtd">

<!--
  ~ Copyright (c) 2007-2018 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help inherits="data/admin/base.enrollment.xml">
	<name>Support Group Administration</name>
	<description>
		This action is an ITSM utility, designed to create or update support groups and to manage their members and related details.
	</description>
	<syntax>
		areasy -action supportgroup.administration
	</syntax>
	<options>
		<option key="operation" type="string" selvalues="setentity,setmembers,delmembers,setfrole,delfrole" defvalue="setentity" description="Execution mode or this action"/>
		<option key="sgroupcompany" type="string" description="Current support group company. In addition the action supports another alias for this option: supportgroupcompany"/>
		<option key="sgrouporganisation" type="string" description="Current support group organisation. In addition the action supports another alias for this option: supportgrouporganisation"/>
		<option key="sgroupname" type="string" description="Current support group name. In addition the action supports some aliases for this option: sgroup, supportgroup, supportgroupname"/>
		<option key="sgroupid" type="string" description="Current support group id. In addition the action supports some aliases for this options: supportgroupid"/>
		<option key="role" type="string" description=""/>
		<option key="apcode" type="string" description="applicationcode"/>
		<option key="status" type="string" description=""/>
		<option key="alias" type="list" description=""/>
		<option key="default" type="bool" description=""/>
		<option key="supportstaff" type="bool" description=""/>
		<option key="findusers" type="bool" description=""/>
	</options>
</help>

=== stefandmn/AREasy/src/doc/help/system/stop.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "../action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help>
	<name>Stop</name>
	<description>
		Start action is used to stop the local AREasy server instance or a remote instance, or to interrupt the execution process of an active action that runs on a specific channel.
		In case of you want to stop a remote instance or an action from a remote instance you have to provide admin credentials (user credentials used to connect to the AR System instance).
	</description>
	<syntax>areasy -action stop [-host AREasyHost -aruser ARSystemUser -arpassword ARSystemPassword] [-channel ExecutionChannel]</syntax>
	<options>
		<option key="host" type="string" description="The host name or IP address where the AREasy server is running"/>
		<option key="aruser" type="string" description="Remedy account name referred by AREasy instance"/>
		<option key="arpassword" type="string" description="Password for Remedy account referred by AREasy instance. The password value could be plain text of obfuscated (encrypted)"/>
		<option key="channel" type="string" description="Execution channel number (i.e. 2) or channel name (i.e. areasy-2)"/>
	</options>
	<samples>
		<sample code="areasy -action stop" description="Stops local server instance or AREasy server instance that is specified in the configuration file"/>
		<sample code="areasy -action stop -host remedysrv.company.com -aruser Demo -arpassword 1234" description="Stops AREasy server instance specified in the command line"/>
		<sample code="areasy -action stop -channel 3" description="Interrupts execution of action that runs on channel 3"/>
	</samples>
</help>

=== stefandmn/AREasy/src/doc/help/action.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE help SYSTEM "action.dtd">

<!--
  ~ Copyright (c) 2007-2020 AREasy Runtime
  ~
  ~ This library, AREasy Runtime and API for BMC Remedy AR System, is free software ("Licensed Software");
  ~ you can redistribute it and/or modify it under the terms of the GNU Lesser General Public
  ~ License as published by the Free Software Foundation; either version 2.1 of the License,
  ~ or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  ~ including but not limited to, the implied warranty of MERCHANTABILITY, NONINFRINGEMENT,
  ~ or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
  -->

<help>
	<options1>
		<option key="action" type="string" description="Runtime action that must be specified in any command line and the action name (the values of this parameter) has to be registered in one of the configuration files (from runtime instance or server instance)"/>
		<option key="host" type="string" defvalue="localhost" description="AREasy server host name"/>
		<option key="port" type="number" defvalue="6506" description="AREasy server TCP/IP port"/>
		<option key="arserver" type="string" defvalue="127.0.0.1" description="AR System server name or IP address for direct connectivity"/>
		<option key="aruser" type="string" defvalue="Demo" description="AR System user name"/>
		<option key="arpassword" type="string" description="User password and value could be plain text of obfuscated (encrypted)"/>
		<option key="arrpc" type="number" description="RPC channel port"/>
		<option key="arport" type="number" defvalue="2300" description="TCP/IP port"/>
		<option key="armode" type="string" selvalues="base,overlay" description="Connectivity mode: base or overlay"/>
		<option key="priority" type="string" selvalues="min,norm, max" description="Sets the priority of the action execution channel. All possible values could be: min (low priority), max (high priority), norm (normal priority)"/>
		<option key="loglevel" type="string" selvalues="debug,info,warn,error" description="Sets logging level of the current action execution session: debug, info, warn or error"/>
		<option key="logformatter" type="string" description="Sets log format of the current action execution session"/>
		<option key="compactmode" type="bool" defvalue="off" description="It sends the data array from server to the AREasy client as a one data line (all values are concatenated in one line, separated by space character)."/>
		<option key="notification" type="bool" defvalue="off" description="Overwrites the standard configuration used to send the output data and the log messages via email. The recipients and all the other email details are specified in the configuration files or could be overwritten by the other parameters (see below). The notification body always will contain the data array generated by the action execution and the action log message. In case of you want to include only data or only the log message use -reportnodata and -reportnolog parameters (see below)"/>
		<option key="reportnodata" type="bool" defvalue="off" description="Ignores in the output message or in the notification body the data array generated by the action execution"/>
		<option key="reportnolog" type="bool" defvalue="off" description="Avoids appending to the output message or to the notification body the log messages generated by the action execution"/>
		<option key="asynchron" type="bool" defvalue="off" description="Launches the action on the server side and don't wait server answer. This parameter works only in client/server mode"/>
		<option key="help" type="bool" description="Displays action's help text. In case of other action than 'help' will use this option, instead of execute the action the runtime will return the help text of that action"/>
		<option key="helplevel" type="number" defvalue="0" description="Specifies if the help text to be generated from a specific level: 0 means only direct options, 1 include also additional options regarding action connectivity and environment, 2 will display also the options that maybe are not relevant for your action but provides all possible option ffrom connectivity and environment point of view"/>
		<option key="helpoptions" type="bool" defvalue="on" description="Prints out the help document containing all options related to the action that is called"/>
		<option key="helpsamples" type="bool" defvalue="on" description="Prints out the help document containing all samples related to the action that is called"/>
	</options1>
	<options2>
		<option key="notificationmailbox" type="string" description="Mailbox name from AR System Email Configuration. It overwrites notification details from AReasy configuration file regarding the mailbox name that will be used (defined in Remedy) to send the notification. So, this parameter could be used only if parameter -notification is specified"/>
		<option key="notificationrecipientto" type="string" description="TO Email address name(s). It overwrites the corresponding notification property from configuration file"/>
		<option key="notificationrecipientcc" type="string" description="CC Email address name(s). It overwrites the corresponding notification property from configuration file"/>
		<option key="notificationsubject" type="string" defvalue="AREasy Runtime Notification" description="Email Subject notification. It overwrites the corresponding notification property from configuration file"/>
		<option key="notificationaction" type="string" description="Submitted notification status (by default is 'Yes', waiting for Remedy server to deliver submitted notification)"/>
		<option key="arremoteserver" type="string" description="Remote AR System server name or IP address referred by AREasy instance"/>
		<option key="arremoteuser" type="string" description="Remote AR System user name"/>
		<option key="arremotepassword" type="string" description="Password for Remote user"/>
		<option key="arremoterpc" type="number" description="RPC channel port for Remote server"/>
		<option key="arremoteport" type="number" description="TCP/IP port for Remote server"/>
		<option key="arremotemode" type="string" selvalues="base,overlay" description="Remote connectivity mode: base or overlay"/>
	</options2>
</help>
